### ISSUE TITLE
Documentação API

### ISSUE THREAD

**Issue by DinosDev** [barbosaadriano/shareflix-api-alurachallenge#1]
Você vai documentar a API?

**Comment by barbosaadriano** [comment]
> Você vai documentar a API?

Talvez sim, o que você me sugere para fazer a documentação?

**Comment by DinosDev** [comment]
Bom, caso você quiser, você pode pegar de exemplo o meu projeto da Alura Challanges - https://github.com/DinosDev/Alura-Challanges-Back-End

**Comment by barbosaadriano** [comment]
> Bom, caso você quiser, você pode pegar de exemplo o meu projeto da Alura Challanges - https://github.com/DinosDev/Alura-Challanges-Back-End

Obrigado @DinosDev, agora sim, realizei a documentação.
